version: '2'

services:
  freepbx-app:
    container_name: freepbx-app
    image: tiredofit/freepbx
    ports:
      - 5060:5060/udp
      - 5160:5160
      - 18000:20000/udp
      - 80:80
    volumes:
      - ~/certs:/certs
      - ~/data:/data
      - ~/logs:/www/logs
      - ~/data/www:/www/freepbx
    environment: 
      - ZABBIX_HOSTNAME=freepbx-app

      - RTP_START=18000
      - RTP_FINISH=20000

      - DB_HOST=freepbx-db
      - DB_NAME=asterisk
      - DB_USER=asterisk
      - DB_PASS=password

      - DEBUG_MODE=TRUE      
    restart: always

  freepbx-db:
    container_name: freepbx-db
    image: tiredofit/mariadb
    restart: always
    volumes:
      - ~/db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=asterisk
      - MYSQL_USER=asterisk
      - MYSQL_PASSWORD=password
