version: '2'

services:
  ldap:
    image: osixia/openldap:1.1.8
    container_name: ldap
    volumes:
      - ldap_data:/var/lib/ldap
      - ldap_slap:/etc/ldap/slapd.d
      - ldap_certs:/container/service/slapd/assets/certs/
    ports:
      - "389:389"
      - "639:639"
    hostname: "ldap"

  phpldapadmin:
    image: osixia/phpldapadmin:0.7.2
    container_name: phpldapadmin
    logging:
      driver: none
    environment:
      - PHPLDAPADMIN_LDAP_HOSTS=ldap
      - PHPLDAPADMIN_HTTPS=false
    ports:
      - "8080:80"
    depends_on:
      - ldap

volumes:
  ldap_data:
  ldap_slap:
  ldap_certs:
