version: '2'

services:
  bind:
    image: sameersbn/bind
    container_name: dns-server
    restart: unless-stopped
    ports:
      - "53:53/udp"
      - "53:53/tcp"
      - "80:80"
      - "10000:10000"
    volumes:
      - ~/bind:/data
