version: '2'

services:
  www:
    image: dimastark/orangeforum
    restart: unless-stopped
    container_name: www
    environment:
      - PG_USER=$PG_USER
      - PG_HOST=$PG_HOST
      - PG_PASS=$PG_PASS
    ports:
      - "80:9123"
