version: '2'

services:
  www:
    image: dimastark/orangeforum
    restart: unless-stopped
    container_name: www
    environment:
      - PG_USER=postgres
      - PG_HOST=$PG_HOST
      - PG_PASS=postgres
    ports:
      - "80:9123"
